# Bitbucket build pipeline - Deprecated
image: php:8.1
pipelines:
  default:
    - step:
        script:
          # Deploy to Downloads the common pipeline script called "run"
          - cd $BITBUCKET_CLONE_DIR
          - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"run"
