name: Algolia Search
on:
  push:
    branches:
      - '**'
    tags:
      - '*'
permissions:
  contents: read
jobs:
  algolia_crawl:
    if: startsWith(github.ref, 'refs/tags/')
    needs: deploy_prod
    runs-on: ubuntu-latest
    env:
      APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
      ALGOLIA_WRITE_API_KEY: ${{ secrets.ALGOLIA_WRITE_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install jq
        run: |
          sudo apt-get update -qy
          sudo apt-get install -y jq

      - name: Run Algolia Crawler for Indexing
        run: |
          CONFIG_JSON=$(jq -r tostring < config.json)
          docker run -i \
            -e "CONFIG=$CONFIG_JSON" \
            -e "APPLICATION_ID=$APPLICATION_ID" \
            -e "API_KEY=$ALGOLIA_WRITE_API_KEY" \
            algolia/docsearch-scraper
