name: 'Composer install'
description: 'Install PHP dependencies for production using Composer'
runs:
  steps:
    #
    # Install external Composer dependencies
    #
    # - Configure workspace as safe for Git, to solve: https://github.com/composer/composer/issues/12221
    # - Composer install will fail if there are other modules in the `vendor` folder. It must run before NPM/Bun install.
    #
    - name: Setup and run Composer install
      uses: php-actions/composer@v6
      with:
        php_version: '8.2'
      run: |
        git config --global --add safe.directory /app
        composer install --no-dev --prefer-dist --no-interaction --no-progress --optimize-autoloader
